Repository r17x/fetch.macro, pull requests merged in 2022-10, with the labels that each got.

#23 feat(fetchText): create test case for fetchText
  README.md
  src/fetch.macro.js
  tests/fetch.js
Labels: hacktoberfest

#28 feat(fetchBlob): add fetchBlob API for produce fetch for blob response
  README.md
  src/fetch.macro.js
  tests/fetch.js
Labels: kodiak: merge.method = 'squash', automerge

#30 chore: create generator API section in readme
  .github/workflows/release.yml
  .husky/generate-api-md
  README.md
  package.json
  tests/fetch.js
  tests/test-cases.js
  yarn.lock
Labels: kodiak: merge.method = 'squash', automerge

#31 feat(fetchFormData): add fetchFormData API for produce fetch for formData response
  README.md
  src/fetch.macro.js
  tests/test-cases.js
Labels: kodiak: merge.method = 'squash', automerge

#34 feat(fetchArrayBuffer): add fetchArrayBuffer API for produce fetch for arrayBuffer response
  README.md
  src/fetch.macro.js
  tests/test-cases.js
Labels: kodiak: merge.method = 'squash', automerge

#36 refactor(transform): simplify apply transform by references
  src/fetch.macro.js
Labels: kodiak: merge.method = 'rebase', automerge

#37 docs(api-generator): using table for generated API example
  .husky/generate-api-md
  README.md
Labels: kodiak: merge.method = 'rebase', automerge

#38 feat(fetchClone): add fetchClone API for produce fetch for cloned response
  README.md
  src/fetch.macro.js
  tests/test-cases.js
Labels: kodiak: merge.method = 'squash', automerge

#52 style: remove unused param type
  src/fetch.macro.js
Labels: kodiak: merge.method = 'rebase', automerge
